package templates

import (
	"time"

	"kube/internal/config"
	"kube/internal/database"
	"kube/pkg/server"
	// "kube/services/your_service" // Replace with your service

	// _ "kube/docs" // Generated by swag init
)

// @title Your Service API
// @version 1.0
// @description Your service description

// @host localhost:8080
// @BasePath /
// @schemes http https

func main() {
	// Load configuration
	cfg := config.Load()
	
	// Initialize database
	db := database.Init(cfg.Database)
	_ = db // Use db in your logic
	
	// Auto migrate models
	// db.AutoMigrate(&models.YourModel{})
	
	// Initialize services
	// yourService := yourservice.NewService(db, cfg.JWT.SecretKey)
	
	// Create server with common configuration
	serverConfig := server.ServerConfig{
		Port:         "8080", // Replace with your port
		ServiceName:  "your-service", // Replace with your service name
		SwaggerURL:   "http://localhost:8080", // Replace with your URL
		RateLimit:    100,
		RateDuration: time.Minute,
	}
	
	srv := server.NewServer(serverConfig)
	
	// Register your routes
	// yourservice.RegisterRoutes(srv.Hertz, yourService)
	
	// Start the server
	srv.Start()
}
