services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: video_streaming
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  user-service-dev:
    build:
      context: ../..
      dockerfile: deployments/docker/Dockerfile.user-service.dev
    ports:
      - "8081:8081"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: video_streaming
      DB_SSLMODE: disable
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: your-secret-key
      JWT_EXPIRES_IN: 24
    volumes:
      # Mount source code for hot reload
      - ../../:/app
      # Exclude node_modules and other unnecessary files
      - /app/node_modules
      - /app/tmp
      - /app/.git
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    command: ["air", "-c", ".air.toml"]

volumes:
  postgres_data:
  redis_data:
